name: Test

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.md"
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}
